MusicInShop.Web/Controllers/OrganizationController.cs
using MusicInShop.BusinessLogic.DataTransfer;
using MusicInShop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicInShop.Web.Controllers
{
    public class OrganizationController : BaseController
    {
        [HttpGet]
        public ActionResult AddProject()
        {
            var model = new ProjectModel { User = LoggedUser };
            return View(model);
        }

        public ActionResult OrganizationPage(string email)
        {
            var model = new OrganizationPageModel { User = LoggedUser, Organization = UserAPI.GetUser(email) };
            return View(model);
        }

        public ActionResult MyProjects()
        {
            var model = new OrganizationProjectModel { User = LoggedUser, Projects = ProjectAPI.GetAllProjects() };
            return View(model);
        }

        [HttpPost]
        public ActionResult AddProject(ProjectModel model)
        {
            if (ModelState.IsValid)
            {
                var project = new ProjectDTO 
                { 
                    Name = model.Name, 
                    Category = model.Category,
                    Description = model.Description,
                    Date = model.Date,
                    Town = model.Town, 
                    Address = model.Address, 
                    OrganizationId = LoggedUser.Id,
                    RequiredNumberOfVolunteers = model.RequiredNumberOfVolunteers, 
                    NumberOfParticipatingVolunteers = 0
                };
                var directory = Server.MapPath("~/Content/img/projects");
                var imgUrl = @"C:\Users\Admin\Desktop\diplom_img\projects\" + (model.ImageUrl ?? "default.png");
                UserAPI.AddProject(project, imgUrl, directory);
                return RedirectToAction("Index", "Project");
            }
            return View(model);
        }

        public ActionResult DeleteProject(int id)
        {
            var directory = Server.MapPath("~/Content/img/projects");
            UserAPI.DeleteProject(id, directory);
            return RedirectToAction("MyProjects");
        }

        public ActionResult ParticipatingVolunteers(int id)
        {
            var projectVolunteers = ProjectVolunteerAPI.GetProjectVolunteersById(id);
            var model = new ParticipatingVolunteersModel { User = LoggedUser, ProjectVolunteers = projectVolunteers };
            return View(model);
        }

        public ActionResult ConfirmParticipant(int id, int projectId)
        {
            UserAPI.ConfirmParticipant(id);
            return RedirectToAction("ParticipatingVolunteers", new { id = projectId });
        }

        public ActionResult DeleteParticipant(int id, int projectId)
        {
            UserAPI.DeleteParticipant(id);
            return RedirectToAction("ParticipatingVolunteers", new { id = projectId });
        }



    }
}

MusicInShop.Web/Views/Organization/AddProject.cshtml
@model MusicInShop.Web.Models.ProjectModel

@{
    ViewBag.Title = "Добавить проект";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <span><img src="~/Content/img/white.png" alt="" height="100"></span>

    <hr />
    <div class="add-proj-box">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category, new SelectList(Enum.GetValues(typeof(Category))), "Выберите категорию")
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Town, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Town, new SelectList(Enum.GetValues(typeof(Locality))), "Выберите город")
                @Html.ValidationMessageFor(model => model.Town, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredNumberOfVolunteers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 num-vol">
                @Html.EditorFor(model => model.RequiredNumberOfVolunteers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredNumberOfVolunteers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 img-marg">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { type = "file" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-4 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default btn-top" />
            </div>
        </div>
    </div>
</div>
}

<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            @*@Html.ActionLink("Вернуться к списку", "Index")*@
        </div>
    </div>
</div>

MusicInShop.Web/Views/Organization/MyProjects.cshtml
@model MusicInShop.Web.Models.OrganizationProjectModel

@{
    ViewBag.Title = "MyProjects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<span><img src="~/Content/img/white.png" alt="" height="120"></span>

<div class="container">
    <div class="row">
        <div class="my-projects-title">
            <h2>Мои проекты</h2>
        </div>
            
    </div>
</div>

<div class="table-class">
    <table class="table">

        @{
            var myProjects = Model.Projects.Where(p => p.Organization.Email == User.Identity.Name).OrderByDescending(y => y.Id);

            foreach (var item in myProjects)
            {
                <tr>
                    <td>
                        <div class="rounded-corners table-margin-img"><img src="@string.Format($"/Content/img/projects/{item.Id}.jpg")" class="img-responsive" width=" 230"></div>
                    </td>
                    <td>
                        <div class="project-name">@Html.DisplayFor(modelItem => item.Name)</div>
                    </td>
                    <td>
                        <div class="participations-hover project-name">
                            <a href="@Url.Action("ParticipatingVolunteers", "Organization", new { id = item.Id })"><p>Участники: &nbsp; <span>@item.NumberOfParticipatingVolunteers</span></p></a>
                        </div>
                    </td>

                    <td>
                        <div class="project-delete"><a>@Html.ActionLink("Удалить", "DeleteProject", new { id = item.Id })</a></div>
                    </td>
                </tr>
            }
         }
    </table>
</div>

MusicInShop.Web/Views/Organization/OrganizationPage.cshtml
@model MusicInShop.Web.Models.OrganizationPageModel

@{
    ViewBag.Title = Model.Organization.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container space-top">
    <div class="project-page-top">
        <div class="image-block">
            <!-- Product Details Left -->
            <div class="product-details-left">
                <div class="product-details-images">
                    <div class="lg-image rounded-corners">
                        <img src="@string.Format($"/Content/img/users/{Model.Organization.Id}.jpg")" alt="">
                    </div>
                </div>
            </div>
            <!--Product Details Left -->
        </div>
        <div class="general-info">
            <div class="col-md-6">
                <!--Product Details Content Start-->
                <div class="product-details-content info-width">

                    <h1 class="title-text-color">@Model.Organization.Name</h1>
                    <span><img src="~/Content/img/white.png" alt="" height="30"></span>

                    <p class="project-page-title">Контакты</p>
                    <h4 class="project-page-text contact-text"><a href="#">@Model.Organization.Email</a></h4>
                    @if (Model.Organization.PhoneNumber != null)
                    {
                        <h4 class="project-page-text contact-text">@Model.Organization.PhoneNumber</h4>
                    }

                    <span><img src="~/Content/img/white.png" alt="" height="30"></span>

                    <p class="project-page-title">Город / село</p>
                    <h4 class="project-page-text">@Model.Organization.Town</h4>

                    <span><img src="~/Content/img/white.png" alt="" height="30"></span>

                </div>
            </div>
        </div>
    </div>
    <div class="col-md-10">
        <!--Product Details Content Start-->
        <div class="product-details-content">

            <span><img src="~/Content/img/white.png" alt="" height="30"></span>

            @if (Model.Organization.Description != null)
            {
                <p class="project-page-title">Описание</p>
                <p class="project-page-text">@Model.Organization.Description</p>

                <span><img src="~/Content/img/white.png" alt="" height="30"></span>
            }


            @if (Model.Organization.Address != null)
            {
                <p class="project-page-title">Адресс</p>
                <h4 class="project-page-text">@Model.Organization.Address</h4>

                <span><img src="~/Content/img/white.png" alt="" height="30"></span>
            }
        </div>
    </div>
</div>

MusicInShop.Web/Views/Organization/ParticipatingVolunteers.cshtml
@model MusicInShop.Web.Models.ParticipatingVolunteersModel

@{
    ViewBag.Title = "MyProjects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<span><img src="~/Content/img/white.png" alt="" height="120"></span>

<div class="container">
    <div class="row">
        <div class="my-projects-title">
            <h2>Участвуют</h2>
        </div>
    </div>
</div>

<div class="volunt-list-org">
    <div class="table-class">
        <table class="table">

            @{
                var volunteers = Model.ProjectVolunteers;

                foreach (var item in volunteers)
                {
                    <tr>
                        <td>
                            <div class="rounded-corners table-margin-img"><img src="@string.Format($"/Content/img/users/{item.VolunteerId}.jpg")" class="img-responsive" width=" 180"></div>
                        </td>
                        <td>
                            <div class="volunt-name">@Html.DisplayFor(modelItem => item.Volunteer.Name) @Html.DisplayFor(modelItem => item.Volunteer.LastName)</div>
                        </td>
                        <td>
                            @{ if (item.Status == 0)
                                {
                                    <div class="volunt-confirm"><a href="@Url.Action("ConfirmParticipant", "Organization", new { id = item.Id, projectId = item.ProjectId })"><p>Подтвердить</p></a></div>
                                }
                                else if (item.Status == 1)
                                {
                                    <div class="volunt-confirmed">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="green"><path d="M20.285 2l-11.285 11.567-5.286-5.011-3.714 3.716 9 8.728 15-15.285z" /></svg>
                                    </div>
                                }
                            }
                        </td>
                        <td>
                            <div class="volunt-delete"><a>@Html.ActionLink("Удалить", "DeleteParticipant", new { id = item.Id, projectId = item.ProjectId })</a></div>
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</div>