MusicInShop.Web/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicInShop.Web.Models;

namespace MusicInShop.Web.Controllers
{
    public class ShopController : BaseController
    {
        public ActionResult Index()
        {
            var model = new ShopModel { User = LoggedUser, Products = ProductAPI.GetAllProducts() };
            return View(model);
        }

        public ActionResult Guitar()
        {
            var model = new ShopModel { User = LoggedUser, Products = ProductAPI.GetAllProducts() };
            return View(model);
        }

        public ActionResult Keyboard()
        {
            var model = new ShopModel { User = LoggedUser, Products = ProductAPI.GetAllProducts() };
            return View(model);
        }

        public ActionResult Violin()
        {
            var model = new ShopModel { User = LoggedUser, Products = ProductAPI.GetAllProducts() };
            return View(model);
        }
        public ActionResult Wind()
        {
            var model = new ShopModel { User = LoggedUser, Products = ProductAPI.GetAllProducts() };
            return View(model);
        }

        public ActionResult Accessories()
        {
            var model = new ShopModel { User = LoggedUser, Products = ProductAPI.GetAllProducts() };
            return View(model);
        }

        public ActionResult Search()
        {
            var model = new ShopModel { User = LoggedUser, Products = ProductAPI.GetAllProducts() };
            return View(model);
        }

        public ActionResult Product(int id)
        {
            var model = new ProductPageModel { User = LoggedUser, Product = ProductAPI.GetProduct(id) };
            return View(model);
        }
        [Authorize]
        public ActionResult Cart()
        {
            var model = new NavbarModel { User = LoggedUser };
            return View(model);
        }
        [Authorize]
        public ActionResult AddToCart(int id, int? quantity)
        {
            UserAPI.AddToCart(User.Identity.Name, id, quantity);
            return PartialView("Empty");
        }
        [Authorize]
        public ActionResult RemoveFromCart(int id)
        {
            UserAPI.RemoveFromCart(User.Identity.Name, id);
            var model = new NavbarModel { User = LoggedUser };
            return PartialView("CartPartial", model);
        }
        [Authorize]
        public ActionResult IncrementToCart(int id)
        {
            UserAPI.AddToCart(User.Identity.Name, id);
            var model = new NavbarModel { User = LoggedUser };
            return PartialView("CartPartial", model);
        }
        [Authorize]
        public ActionResult DecrementFromCart(int id)
        {
            UserAPI.DecrementFromCart(User.Identity.Name, id);
            var model = new NavbarModel { User = LoggedUser };
            return PartialView("CartPartial", model);
        }
    }
}

MusicInShop.Web/Controllers/UserController.cs
using MusicInShop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicInShop.Web.Controllers
{
    public class UserController : BaseController
    {
        // GET: User
        public ActionResult OrganizationPage()
        {
            var model = new UserPageModel { User = LoggedUser, Users = UserAPI.GetAllUsers() };
            return View(model);
        }

        public ActionResult VolunteerPage()
        {
            var model = new UserPageModel { User = LoggedUser, Users = UserAPI.GetAllUsers() };
            return View(model);
        }
    }
}

MusicInShop.Web/Views/Shared/_Footer.cshtml
<div id="social">
    <div class="container">
        <div class="row centered">
            <div class="col-lg-2">
                <a href="https://www.instagram.com/staschernioglo/"><i class="fa fa-dribbble"></i></a>
            </div>
            <div class="col-lg-2">
                <a href="https://www.facebook.com/stanislav.chernioglo.5"><i class="fa fa-facebook"></i></a>
            </div>
            <div class="col-lg-2">
                <a href="https://www.instagram.com/staschernioglo/"><i class="fa fa-twitter"></i></a>
            </div>
            <div class="col-lg-2">
                <a href="https://www.instagram.com/staschernioglo/"><i class="fa fa-linkedin"></i></a>
            </div>
            <div class="col-lg-2">
                <a href="https://www.instagram.com/staschernioglo/"><i class="fa fa-instagram"></i></a>
            </div>
            <div class="col-lg-2">
                <a href="https://www.instagram.com/staschernioglo/"><i class="fa fa-tumblr"></i></a>
            </div>

        </div>
    </div>
</div>

<div id="copyrights">
    <div class="container">
        <ul style="color: white;">
            <li><h3></h3></li>
            <li><h3 class="white-text">Be Happy!</h3></li>
            <li><h3></h3> </li>
        </ul>

        <div class="credits">
            <!--
          You are NOT allowed to delete the credit link to TemplateMag with free version.
          You can delete the credit link only if you bought the pro version.
          Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/instant-bootstrap-personal-template/
          Licensing information: https://templatemag.com/license/
        -->

        </div>
    </div>
</div>

MusicInShop.Web/Views/Shared/_Header.cshtml
@model NavbarModel
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/Home/Index"><img src="/Content/img/logo.png" width="170" ></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left help-me-cl">
                <li class="dropdown">
                    <a id="drop1" href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <div id="mobile_nav_icon"></div>
                         Меню
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("Index","Project")">Проекты</a></li>
                        <li class="divider"></li>
                        <li><a href="@Url.Action("Index","GoodDeed")">Добрые дела</a></li>
                        <li class="divider"></li>
                        <li><a href="@Url.Action("OrganizationPage","User")">Волонтёрские организации</a></li>
                        <li class="divider"></li>
                        <li><a href="@Url.Action("VolunteerPage","User")">Волонтёры</a></li>
                    </ul>
                </li>
                <li>
                    @*<div class="d7">
                        <form>
                            <input type="text" placeholder="Поиск" text_color="black">
                            <a href="@Url.Action("Search","Shop")"class="glyphicon glyphicon-search" aria-hidden="true" style="color: black;"></a>
                        </form>
                    </div>*@
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    @*@if (User.Identity.IsAuthenticated)
                    {
                        <a>@Model.User.Email</a>
                    }*@

                    @if (User.Identity.IsAuthenticated)
                    {
                        if (Model.User.Role == "admin")
                        {
                        <li><a href="@Url.Action("Index", "Admin")">Панель админа</a></li>
                    }
                    else
                    if (Model.User.Role == "organization")
                    {
                        <li><a class="help-me-cl" href="@Url.Action("AddProject", "Organization")">Добавить проект</a></li>
                    }
                    else if (Model.User.Role == "volunteer")
                    {
                        <li><a class="help-me-cl" href="#">Добавить доброе дело</a></li>
                    }
                    else if (Model.User.Role == "user")
                    {
                        <li><a class="help-me-cl" href="@Url.Action("AddGoodDeed", "SimpleUser")">Попросить о помощи</a></li>
                    }

                    <li class="dropdown">
                        <a id="drop1" href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <svg width="1.4em" height="1.2em" viewBox="0 0 16 16" class="bi bi-caret-down-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M3.544 6.295A.5.5 0 0 1 4 6h8a.5.5 0 0 1 .374.832l-4 4.5a.5.5 0 0 1-.748 0l-4-4.5a.5.5 0 0 1-.082-.537z" />
                                <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                            </svg>
                        </a>
                        <ul class="dropdown-menu">
                            @if (Model.User.Role == "organization")
                            {
                                <li><a href="@Url.Action("MyProjects", "Organization")">Мои проекты</a></li>
                                <li class="divider"></li>
                            }

                            @if (Model.User.Role == "volunteer")
                            {
                                <li><a href="@Url.Action("MyParticipations", "Volunteer", new { email = User.Identity.Name })">Мои участия</a></li>
                                <li class="divider"></li>
                            }

                            <li><a href="@Url.Action("Logoff", "Account")">Выйти &nbsp;&nbsp;<i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
                        </ul>
                    </li>
                }

                else
                {
                    <li><a href="@Url.Action("Login", "Account")">Войти</a></li>
                    <li><a href="/Account/RegisterType">Зарегистрироваться</a></li>
                }
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>

MusicInShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Chukundur</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicons -->
    <link href="img/favicon.png" rel="icon">
    <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700" rel="stylesheet">

    <!-- Bootstrap CSS File -->
    <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Libraries CSS Files -->
    <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <!-- Main Stylesheet File -->
    <link href="css/style.css" rel="stylesheet">


    @Styles.Render("~/bundles/css")
</head>

<body>
    @Html.Partial("_Header")

    <div>
        @RenderBody().
    </div>

    @Html.Partial("_Footer")


    @Scripts.Render("~/bundles/js")


</body>
</html>